import React,{useEffect,useMemo,useState}from'react';
import{useNavigate}from'react-router-dom';
import{api}from'./api';
import type{EnterpriseSummary,EnterpriseWorkspace,ReleaseDecision,RadarRow,Run}from'./types';
import{Building2,ShieldCheck,GitPullRequest,ServerCog,Boxes,ArrowUpRight,CheckCircle2,TriangleAlert,Network,Database,LockKeyhole}from'lucide-react';

const Badge=({v}:{v:string})=><span className={'status '+(v==='PROMOTE'?'PASS':v==='BLOCK'?'BLOCK':v==='HOLD'?'REVIEW':'')}>{v}</span>;
const Card=({title,value,sub}:{title:string;value:string|number;sub:string})=><div className="panel kpi"><div className="kTop"><span>{title}</span><ServerCog size={12}/></div><div className="kVal">{value}</div><div className="kSub">{sub}</div></div>;
const Row=({l,v}:{l:string;v:React.ReactNode})=><div className="row"><span>{l}</span><b>{v}</b></div>;

export function EnterprisePage(){
 const[summary,setSummary]=useState<EnterpriseSummary|null>(null),[workspaces,setWorkspaces]=useState<EnterpriseWorkspace[]>([]),[radar,setRadar]=useState<RadarRow[]>([]),[releases,setReleases]=useState<ReleaseDecision[]>([]),[incidents,setIncidents]=useState<any[]>([]);const go=useNavigate();
 useEffect(()=>{Promise.all([api.enterpriseSummary(),api.enterpriseWorkspaces(),api.enterpriseRadar(),api.enterpriseReleases(),api.enterpriseIncidents()]).then(([s,w,r,rel,i])=>{setSummary(s);setWorkspaces(w);setRadar(r);setReleases(rel);setIncidents(i)})},[]);
 return <><div className="header"><div><div className="eye">ENTERPRISE CONTROL PLANE</div><h1>From model change to governed release.</h1><div className="desc">Portfolio-level evidence, deployment metadata, release decisions and audit receipts across client use cases.</div></div><div className="actions"><span className="pill"><ShieldCheck size={11}/> FAIL-CLOSED</span></div></div>
 <div className="grid g4"><Card title="Workspaces" value={summary?.workspaces??'—'} sub="client/use-case isolation scaffold"/><Card title="Evidence runs" value={summary?.benchmark_runs??'—'} sub="persistent benchmark ledger"/><Card title="Promoted releases" value={summary?.promoted_releases??'—'} sub="explicit release receipts"/><Card title="Blocked candidates" value={summary?.blocked_candidates??'—'} sub="hard gates stopped promotion"/></div>
 <div className="grid g2" style={{marginTop:12}}><div className="panel"><div className="sectionHead"><div><h2>Enterprise workspaces</h2><div className="muted">Deployment posture and integration boundary</div></div></div><div className="tableWrap"><table className="table"><thead><tr><th>Workspace</th><th>Use case</th><th>Env</th><th>Deploy</th><th>Criticality</th></tr></thead><tbody>{workspaces.map(w=><tr key={w.id}><td>{w.name}<div className="muted">{w.integration}</div></td><td>{w.use_case}</td><td>{w.environment}</td><td>{w.deployment}</td><td>{w.criticality}</td></tr>)}</tbody></table></div></div>
 <div className="panel pad"><h2>Model radar</h2>{radar.map(r=><Row key={r.model_id} l={r.model_id} v={<span>{r.state} · {r.pass} pass / {r.block} block</span>}/>)}<button className="btn" style={{marginTop:10}} onClick={()=>go('/models')}>Open model evidence <ArrowUpRight size={10}/></button></div></div>
 <div className="grid g2" style={{marginTop:12}}><div className="panel pad"><h2>Latest release decisions</h2>{releases.length?releases.slice(0,5).map(r=><div className="releaseLine" key={r.id}><div><b>{r.candidate_model_id}</b><div className="muted">{r.workspace_id} · {r.environment} · {r.run_id}</div></div><Badge v={r.decision}/></div>):<div className="notice">No release receipt yet. Create one from Release Center after a benchmark run.</div>}<button className="btn primary" style={{marginTop:10}} onClick={()=>go('/release-center')}>Release Center</button></div>
 <div className="panel pad"><h2>Active quality incidents</h2>{incidents.length?incidents.slice(0,5).map(i=><div className="reason" key={i.id}><b>{i.title}</b><div className="muted">{i.use_case} · {i.model_id} · {i.reasons.join(', ')}</div></div>):<div className="notice"><CheckCircle2 size={11}/> No blocking evidence in current ledger.</div>}</div></div></>;
}

export function ReleaseCenter(){
 const[runs,setRuns]=useState<Run[]>([]),[workspaces,setWorkspaces]=useState<EnterpriseWorkspace[]>([]),[releases,setReleases]=useState<ReleaseDecision[]>([]),[runId,setRunId]=useState(''),[candidate,setCandidate]=useState(''),[workspace,setWorkspace]=useState('coalbrain-lab'),[busy,setBusy]=useState(false),[receipt,setReceipt]=useState<ReleaseDecision|null>(null);
 const load=()=>Promise.all([api.runs(),api.enterpriseWorkspaces(),api.enterpriseReleases()]).then(([r,w,rel])=>{setRuns(r);setWorkspaces(w);setReleases(rel);if(!runId&&r[0])setRunId(r[0].id)});useEffect(()=>{load()},[]);
 const selected=useMemo(()=>runs.find(r=>r.id===runId),[runs,runId]);useEffect(()=>{if(selected?.candidates[0])setCandidate(selected.candidates[0].model_id)},[runId,selected]);
 async function decide(){if(!selected||!candidate)return;setBusy(true);try{const r=await api.createRelease({run_id:selected.id,candidate_model_id:candidate,workspace_id:workspace,environment:'pilot',requested_by:'portfolio-operator'});setReceipt(r);await load()}finally{setBusy(false)}}
 return <><div className="header"><div><div className="eye">RELEASE CENTER</div><h1>Turn benchmark evidence into a release decision.</h1><div className="desc">A release receipt records incumbent, challenger, deltas, policy and the final PROMOTE/HOLD/BLOCK state.</div></div><span className="pill"><GitPullRequest size={11}/> HUMAN-READABLE RECEIPTS</span></div>
 <div className="split"><div className="panel pad"><h2>Decision input</h2><div className="form"><label className="field"><span>Benchmark run</span><select value={runId} onChange={e=>setRunId(e.target.value)}>{runs.map(r=><option key={r.id} value={r.id}>{r.id} · {r.use_case}</option>)}</select></label><label className="field"><span>Candidate</span><select value={candidate} onChange={e=>setCandidate(e.target.value)}>{selected?.candidates.map(c=><option key={c.model_id}>{c.model_id}</option>)}</select></label><label className="field"><span>Workspace</span><select value={workspace} onChange={e=>setWorkspace(e.target.value)}>{workspaces.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label></div><button className="btn primary" style={{marginTop:12}} onClick={decide} disabled={busy||!selected}>{busy?'Evaluating…':'Create release receipt'}</button></div>
 <div className="panel pad"><h2>Current evidence</h2>{selected&&candidate?(()=>{const c=selected.candidates.find(x=>x.model_id===candidate);return c?<><Row l="Benchmark gate" v={<span className={'status '+c.status}>{c.status}</span>}/><Row l="Critical accuracy" v={c.metrics.critical_accuracy+'%'}/><Row l="Cost delta" v={c.cost_delta_pct+'%'}/><Row l="Security failures" v={c.metrics.security_failures}/><Row l="Unsafe auto-action" v={c.metrics.unsafe_auto_action+'%'}/></>:null})():<div className="muted">Select evidence.</div>}</div></div>
 {receipt&&<div className="panel pad" style={{marginTop:12}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><h2>Release receipt</h2><div className="muted mono">{receipt.id}</div></div><Badge v={receipt.decision}/></div><div className="grid g4" style={{marginTop:10}}><Card title="Quality Δ" value={receipt.quality_delta+'pp'} sub="critical accuracy vs incumbent"/><Card title="Cost Δ" value={receipt.cost_delta_pct+'%'} sub="per task vs incumbent"/><Card title="P95 Δ" value={receipt.p95_latency_delta_ms+'ms'} sub="latency vs incumbent"/><Card title="Environment" value={receipt.environment} sub={receipt.workspace_id}/></div><div className="notice" style={{marginTop:10}}>{receipt.reasons.join(' · ')}</div></div>}
 <div className="panel" style={{marginTop:12}}><div className="sectionHead"><h2>Decision ledger</h2></div><div className="tableWrap"><table className="table"><thead><tr><th>Decision</th><th>Candidate</th><th>Workspace</th><th>Run</th><th>Quality Δ</th><th>Cost Δ</th></tr></thead><tbody>{releases.map(r=><tr key={r.id}><td><Badge v={r.decision}/></td><td>{r.candidate_model_id}</td><td>{r.workspace_id}</td><td className="mono">{r.run_id}</td><td>{r.quality_delta}pp</td><td>{r.cost_delta_pct}%</td></tr>)}</tbody></table></div></div></>;
}
export function CoalbrainFitPage(){
 const packs=[
  {name:'AI Fakturant / document processing',match:'HIGH',evidence:'Invoice extraction golden sets, critical-field gates, prompt-injection tests, human review for low confidence.',next:'Connect anonymized client samples and exact ERP schemas.'},
  {name:'Order automation / logistics',match:'HIGH',evidence:'Agent traces, approval-before-ERP hard gate, tool ordering, regression promotion.',next:'Add Prytanis/SAP/HELIOS adapter contract tests.'},
  {name:'AI Zapisovatel',match:'HIGH',evidence:'Meeting decisions/tasks/owners/deadlines, fabricated-task rate and abstention quality.',next:'Add ASR/diarization-specific datasets and domain vocabulary.'},
  {name:'Coalshift',match:'HIGH',evidence:'Shift constraint scenarios with legal-rest and qualification hard gates plus soft fairness metrics.',next:'Add solver-level deterministic constraint certificates.'},
  {name:'AI opportunity analysis',match:'MEDIUM',evidence:'Can attach measured pilot evidence and release risk to a client roadmap.',next:'Add ROI assumptions, process discovery import and executive PDF export.'},
 ];
 return <><div className="header"><div><div className="eye">COALBRAIN REFERENCE PACK</div><h1>Is AI Evidence Gate useful for Coalbrain?</h1><div className="desc">Yes, as a cross-product quality and release layer behind the workflows Coalbrain publicly describes. This page is an independent fit assessment, not an affiliation claim.</div></div><span className="pill"><Building2 size={11}/> PUBLIC USE-CASE MAPPING</span></div>
 <div className="panel"><div className="tableWrap"><table className="table"><thead><tr><th>Public workflow</th><th>Fit</th><th>What AI Evidence Gate already covers</th><th>Production gap</th></tr></thead><tbody>{packs.map(p=><tr key={p.name}><td><b>{p.name}</b></td><td><span className="pill">{p.match}</span></td><td>{p.evidence}</td><td>{p.next}</td></tr>)}</tbody></table></div></div>
 <div className="grid g3" style={{marginTop:12}}><div className="panel pad"><ShieldCheck size={17}/><h2 style={{marginTop:8}}>Why it fits</h2><div className="muted">Coalbrain sells outcomes across documents, meetings, scheduling and agentic automation. One shared eval layer prevents every product from inventing its own quality logic.</div></div><div className="panel pad"><Network size={17}/><h2 style={{marginTop:8}}>Where it sits</h2><div className="muted">Between model/provider changes and production workflows: replay → grade → gate → release receipt → regression feedback.</div></div><div className="panel pad"><TriangleAlert size={17}/><h2 style={{marginTop:8}}>What it is not</h2><div className="muted">Not a replacement for product-specific business logic, ERP validation, solver constraints, SSO, secrets management or client security review.</div></div></div></>;
}

export function ScaffoldPage(){
 const layers=[['Experience','Enterprise dashboard · Release Center · reports'],['Control plane','Workspaces · model radar · policies · audit'],['Evaluation','Datasets · regressions · graders · traces · security'],['Execution','Provider adapters · deterministic demo · client/on-prem boundary'],['Persistence','PostgreSQL · immutable-ish receipts · version metadata'],['Delivery','Docker Compose · CI · Playwright · health/readiness']];
 return <><div className="header"><div><div className="eye">ENTERPRISE MVP SCAFFOLD</div><h1>One product, explicit trust boundaries.</h1><div className="desc">A deployable reference architecture that can grow into multi-tenant production without pretending the unfinished controls already exist.</div></div><span className="pill"><Boxes size={11}/> MVP ENTERPRISE</span></div>
 <div className="grid g3">{layers.map(([a,b])=><div className="panel pad" key={a}><h2>{a}</h2><div className="muted">{b}</div></div>)}</div>
 <div className="grid g2" style={{marginTop:12}}><div className="panel pad"><h2>Implemented now</h2>{['Persistent evidence + regression corpus','Editable release policies','Enterprise workspace metadata','PROMOTE / HOLD / BLOCK receipts','Model radar and blocked incidents','Audit ledger','Provider configuration boundary','Docker health/readiness','Browser E2E scaffold'].map(x=><div className="row" key={x}><span>{x}</span><CheckCircle2 size={13}/></div>)}</div>
 <div className="panel pad"><h2>Production hardening backlog</h2>{['OIDC/SSO + enforceable RBAC','Secrets manager / KMS','Row-level tenant isolation','Real client dataset ingestion pipeline','PII redaction + retention policy','OpenTelemetry + alerting','Backup/restore drills','Signed release attestations','HA deployment + SLOs'].map(x=><div className="row" key={x}><span>{x}</span><span className="status REVIEW">NEXT</span></div>)}</div></div></>;
}
