import React,{useEffect,useMemo,useState}from'react';
import{useNavigate,useParams}from'react-router-dom';
import{Play,ShieldCheck,CheckCircle2,TriangleAlert,ArrowRight,HelpCircle,FlaskConical,GitPullRequest}from'lucide-react';
import{api}from'./api';
import type{Dataset,Model,Policy,Run,ReleaseDecision,EnterpriseWorkspace}from'./types';

const useCaseLabel:Record<string,string>={invoice:'Zpracování faktur a dokladů',meeting:'Zápis ze schůzek',shift:'Plánování směn',agent_order:'Zpracování objednávek'};
const gateCopy={PASS:{title:'Prošlo kontrolou',tone:'PASS',text:'Kandidát splnil nastavené limity kvality a bezpečnosti. Může pokračovat k rozhodnutí o nasazení.'},REVIEW:{title:'Potřebuje lidskou kontrolu',tone:'REVIEW',text:'Kritické podmínky nejsou porušené, ale některá oblast vyžaduje posouzení člověkem.'},BLOCK:{title:'Nenasazovat',tone:'BLOCK',text:'Kontrola našla závažný problém. Kandidát nemá pokračovat do produkce.'}} as const;
const releaseCopy={PROMOTE:{title:'Lze nasadit',tone:'PASS',text:'Důkazy splňují pravidla pro zvolený proces.'},HOLD:{title:'Pozastavit a zkontrolovat',tone:'REVIEW',text:'Před nasazením je potřeba lidské posouzení.'},BLOCK:{title:'Nenasazovat',tone:'BLOCK',text:'Nasazení blokuje závažný problém.'},UNKNOWN:{title:'Nelze rozhodnout',tone:'REVIEW',text:'Chybí dostatek důkazů pro bezpečné rozhodnutí.'}} as const;
const pct=(n:number)=>n.toFixed(2)+' %';

function Hero({title,desc,action}:{title:string;desc:string;action?:React.ReactNode}){return <div className="header simpleHeader"><div><div className="eye">AI EVIDENCE GATE</div><h1>{title}</h1><div className="desc simpleDesc">{desc}</div></div>{action&&<div className="actions">{action}</div>}</div>}
function SimpleStatus({status}:{status:'PASS'|'REVIEW'|'BLOCK'}){const c=gateCopy[status];return <div className={'simpleDecision '+c.tone}><b>{c.title}</b><span>{c.text}</span></div>}
function Metric({label,value,help}:{label:string;value:string;help:string}){return <div className="panel simpleMetric"><div className="muted">{label}</div><div className="simpleMetricValue">{value}</div><div className="simpleMetricHelp">{help}</div></div>}

export function SimpleOverview(){const[runs,setRuns]=useState<Run[]>([]),[releases,setReleases]=useState<ReleaseDecision[]>([]);const go=useNavigate();useEffect(()=>{Promise.all([api.runs(),api.enterpriseReleases()]).then(([r,rel])=>{setRuns(r);setReleases(rel)})},[]);const last=runs[0]?.candidates[0];return <><section className="hero2026"><div className="heroCopy"><div className="heroBadge"><ShieldCheck size={13}/> Bezpečnější změny AI před produkcí</div><h1>Ověřte AI změnu dřív, než ji pustíte do provozu.</h1><p>Porovnejte současnou a novou variantu na stejných případech. AI Evidence Gate zkontroluje kvalitu, bezpečnost, cenu i rychlost a vrátí jasný verdikt.</p><div className="heroActions"><button className="btn primary heroCta" onClick={()=>go('/run')}><Play size={15}/> Spustit novou kontrolu</button><button className="btn heroSecondary" onClick={()=>go('/jak-to-funguje')}><HelpCircle size={14}/> Jak to funguje</button></div><div className="trustStrip"><span><CheckCircle2 size={13}/> Kritické chyby blokují nasazení</span><span><CheckCircle2 size={13}/> Výsledek je dohledatelný</span><span><CheckCircle2 size={13}/> Demo běží bez externích klíčů</span></div></div><div className="heroVerdict panel"><div className="heroVerdictTop"><span>Ukázkový výsledek</span><span className="status PASS">PROŠLO</span></div><div className="heroVerdictScore">99,7 %</div><div className="heroVerdictLabel">kritická přesnost</div><div className="heroMiniGrid"><div><b>0</b><span>bezpečnostních chyb</span></div><div><b>−18 %</b><span>nákladů / úlohu</span></div></div><div className="heroVerdictFoot">Nejde o univerzální leaderboard. Rozhoduje konkrétní proces a jeho pravidla.</div></div></section>
<div className="journey"><div><span>1</span><b>Vyberete proces</b><small>např. faktury nebo objednávky</small></div><ArrowRight/><div><span>2</span><b>Porovnáme varianty</b><small>stejná data, stejná pravidla</small></div><ArrowRight/><div><span>3</span><b>Dostanete jasný verdikt</b><small>prošlo / zkontrolovat / blokovat</small></div></div>
<div className="grid g3 simpleGrid valueCards"><div className="panel pad"><div className="featureIcon"><ShieldCheck size={18}/></div><h2>Hlídá to důležité</h2><p>Kritická data, halucinace, bezpečnost, cenu a latenci. Nejen průměrné skóre.</p></div><div className="panel pad"><div className="featureIcon"><FlaskConical size={18}/></div><h2>Porovnává férově</h2><p>Současná i nová varianta dostanou stejné případy a stejná pravidla.</p></div><div className="panel pad"><div className="featureIcon"><GitPullRequest size={18}/></div><h2>Řekne, co dál</h2><p>Prošlo, potřebuje člověka, nebo blokovat. Výsledek se uloží jako auditní důkaz.</p></div></div>
<div className="grid g2 homeBottom" style={{marginTop:14}}><div className="panel pad"><div className="sectionEyebrow">AKTUÁLNÍ STAV</div><h2>Poslední kontrola</h2>{last?<><SimpleStatus status={last.status}/><button className="btn softCta" style={{marginTop:12}} onClick={()=>go('/results')}>Otevřít výsledky <ArrowRight size={12}/></button></>:<div className="emptyState"><div className="emptyIcon"><FlaskConical size={18}/></div><b>Zatím žádná kontrola</b><span>První kontrola zabere jen několik kliknutí.</span><button className="btn primary" onClick={()=>go('/run')}>Spustit první kontrolu</button></div>}</div><div className="panel pad"><div className="sectionEyebrow">DŮVĚRYHODNOST</div><h2>Co se ukládá a proč</h2><p className="plainText">Výsledek, použitá pravidla, verze testovací sady, auditní stopa a rozhodnutí o nasazení. Později je tak možné doložit, proč změna prošla nebo neprošla.</p><div className="evidenceStats"><div><b>{runs.length}</b><span>evidovaných kontrol</span></div><div><b>{releases.length}</b><span>rozhodnutí o nasazení</span></div></div></div></div>
<div className="demoBanner"><ShieldCheck size={15}/><div><b>Bezpečný demo režim.</b> Veřejné MVP používá syntetická data. Reálné provider volání je vypnuté, dokud není explicitně nakonfigurované.</div></div></>}

export function SimpleRun(){const[models,setModels]=useState<Model[]>([]),[datasets,setDatasets]=useState<Dataset[]>([]),[policies,setPolicies]=useState<Policy[]>([]),[uc,setUc]=useState('invoice'),[base,setBase]=useState('atlas-large'),[cand,setCand]=useState('vision-extractor'),[ds,setDs]=useState('invoice-cz-v4'),[pol,setPol]=useState('enterprise-strict'),[busy,setBusy]=useState(false),[advanced,setAdvanced]=useState(false);const go=useNavigate();useEffect(()=>{Promise.all([api.models(),api.datasets(),api.policies()]).then(([m,d,p])=>{setModels(m);setDatasets(d);setPolicies(p)})},[]);useEffect(()=>{const d=datasets.find(x=>x.use_case===uc);if(d)setDs(d.id)},[uc,datasets]);useEffect(()=>{if(cand===base){const other=models.find(m=>m.id!==base);if(other)setCand(other.id)}},[base,models]);async function run(){setBusy(true);try{const r=await api.run({use_case:uc,baseline_model_id:base,candidate_model_ids:[cand],dataset_id:ds,policy_id:pol,seed:4242});go('/results/'+r.id)}finally{setBusy(false)}}return <><Hero title="Nová kontrola" desc="Stačí vybrat, co testujeme, současné řešení a novou variantu. O zbytek se postará kontrolní sada."/>
<div className="simpleSteps"><div className="panel pad"><div className="stepBadge">1</div><h2>Co chcete ověřit?</h2><label className="field"><span>Firemní proces</span><select value={uc} onChange={e=>setUc(e.target.value)}>{Object.entries(useCaseLabel).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><div className="helper">Vyberte proces, ve kterém má AI pracovat. Každý má jiné kritické podmínky.</div></div>
<div className="panel pad"><div className="stepBadge">2</div><h2>Co srovnáváme?</h2><label className="field"><span>Současná varianta</span><select value={base} onChange={e=>setBase(e.target.value)}>{models.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label className="field" style={{marginTop:10}}><span>Nová varianta</span><select value={cand} onChange={e=>setCand(e.target.value)}>{models.filter(m=>m.id!==base).map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><div className="helper">Novou variantu testujeme na stejných případech jako současné řešení.</div></div>
<div className="panel pad"><div className="stepBadge">3</div><h2>Spusťte kontrolu</h2><div className="helper strongHelper">Použijeme doporučenou kontrolní sadu pro tento proces. Kritická chyba vždy blokuje pokračování, i kdyby byla nová varianta levnější nebo rychlejší.</div><button data-testid="simple-run" className="btn primary bigCta" style={{marginTop:14,width:'100%'}} onClick={run} disabled={busy}>{busy?'Probíhá kontrola…':'Spustit bezpečnou kontrolu'}</button><button className="btn advancedToggle" type="button" onClick={()=>setAdvanced(v=>!v)}>{advanced?'Skrýt technické nastavení':'Pokročilé nastavení'}</button>{advanced&&<div className="advancedBox"><label className="field"><span>Testovací sada</span><select value={ds} onChange={e=>setDs(e.target.value)}>{datasets.filter(d=>d.use_case===uc).map(d=><option key={d.id} value={d.id}>{d.name} · v{d.version}</option>)}</select></label><label className="field" style={{marginTop:10}}><span>Kontrolní pravidla</span><select value={pol} onChange={e=>setPol(e.target.value)}>{policies.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><div className="muted" style={{marginTop:8}}>Tyto volby jsou určeny pro správce kvality. Pro běžnou kontrolu je není potřeba měnit.</div></div>}</div></div>
<div className="simpleNote"><b>Co se stane po kliknutí?</b> Obě varianty dostanou stejné případy. Systém změří kvalitu, bezpečnost, cenu a rychlost a vrátí jasný verdikt s doporučeným dalším krokem.</div></>}

export function SimpleResults(){const[runs,setRuns]=useState<Run[]>([]);const go=useNavigate();useEffect(()=>{api.runs().then(setRuns)},[]);const rows=runs.flatMap(r=>r.candidates.map(c=>({r,c})));return <><Hero title="Výsledky kontrol" desc="Každý řádek říká, co jsme testovali a jestli nová varianta splnila pravidla." action={<button className="btn primary" onClick={()=>go('/run')}><Play size={12}/> Nová kontrola</button>}/><div className="resultCards">{rows.map(({r,c})=>{const copy=gateCopy[c.status];return <button className="panel resultCard" key={r.id+c.model_id} onClick={()=>go('/results/'+r.id)}><div><div className="muted">{new Date(r.created_at).toLocaleString('cs-CZ')}</div><h2>{useCaseLabel[r.use_case]||r.use_case}</h2><div className="plainText">Nová varianta: <b>{c.model_id}</b> · proti: {r.baseline_model_id}</div></div><div className={'status '+copy.tone}>{copy.title}</div></button>})}</div>{!rows.length&&<div className="panel pad"><div className="notice">Zatím tu nejsou žádné kontroly.</div></div>}</>}

export function SimpleResultDetail(){const{id}=useParams(),[run,setRun]=useState<Run|null>(null);const go=useNavigate();useEffect(()=>{if(id)api.runDetail(id).then(setRun)},[id]);if(!run)return <Hero title="Načítám výsledek…" desc=""/>;const c=run.candidates[0],copy=gateCopy[c.status];return <><Hero title={useCaseLabel[run.use_case]||'Výsledek kontroly'} desc={`Porovnání ${c.model_id} proti ${run.baseline_model_id}.`} action={<div className={'status '+copy.tone}>{copy.title}</div>}/><SimpleStatus status={c.status}/>
<div className="grid g4 simpleGrid" style={{marginTop:12}}><Metric label="Kritická přesnost" value={pct(c.metrics.critical_accuracy)} help="Správnost údajů, kde chyba může mít vážný dopad."/><Metric label="Dodržení formátu" value={pct(c.metrics.schema_compliance)} help="Jak často výstup odpovídá očekávané struktuře."/><Metric label="Bezpečnostní chyby" value={String(c.metrics.security_failures)} help="Kritické bezpečnostní selhání blokuje nasazení."/><Metric label="Změna ceny" value={c.cost_delta_pct+' %'} help="Rozdíl nákladů proti současné variantě."/></div>
<div className="grid g2" style={{marginTop:12}}><div className="panel pad"><h2>Proč systém rozhodl právě takto?</h2>{c.reasons.length?c.reasons.map((r,i)=><div className="reason" key={i}><b>{humanMetric(r.metric)}</b><div className="muted">Naměřeno: {String(r.actual)} · požadavek: {r.expected}</div></div>):<div className="notice"><CheckCircle2 size={12}/> Všechna nastavená pravidla byla splněna.</div>}</div><div className="panel pad"><h2>Co dál?</h2>{c.status==='PASS'?<><p className="plainText">Výsledek může pokračovat k samostatnému rozhodnutí o nasazení. To vytvoří auditovatelný záznam pro konkrétní proces.</p><button className="btn primary" onClick={()=>go('/release-center')}>Pokračovat k rozhodnutí <ArrowRight size={11}/></button></>:<><p className="plainText">Tuto variantu teď neposílejte dál. Nejprve opravte důvod selhání nebo ho nechte posoudit člověkem.</p><button className="btn" onClick={()=>go('/run')}>Spustit jinou kontrolu</button></>}</div></div>
<details className="advancedDisclosure"><summary>Technické detaily kontroly</summary><div className="auditPayload">{JSON.stringify({kontrola:run.id,testovaci_sada:`${run.dataset_id}@${run.dataset_version}`,pravidla:`${run.policy_id}@${run.policy_version}`,seed:run.seed,prompt:run.prompt_version,build:run.build_version},null,2)}</div><div className="muted" style={{marginTop:8}}>Tyto údaje slouží k opakovatelnosti a auditu. Pro běžné rozhodnutí je nemusíte řešit.</div></details></>}

function humanMetric(m:string){const x:Record<string,string>={critical_accuracy:'Kritická přesnost',schema_compliance:'Dodržení formátu',fabricated_rate:'Vymyšlené údaje',security_failures:'Bezpečnostní chyby',unsafe_auto_action:'Nebezpečná automatická akce',p95_latency_ms:'Rychlost odpovědi',cost_regression_pct:'Nárůst ceny'};return x[m]||m}

export function SimpleRelease(){const[runs,setRuns]=useState<Run[]>([]),[workspaces,setWorkspaces]=useState<EnterpriseWorkspace[]>([]),[runId,setRunId]=useState(''),[workspace,setWorkspace]=useState('coalbrain-lab'),[receipt,setReceipt]=useState<ReleaseDecision|null>(null),[busy,setBusy]=useState(false);useEffect(()=>{Promise.all([api.runs(),api.enterpriseWorkspaces()]).then(([r,w])=>{setRuns(r);setWorkspaces(w);const first=r.find(x=>x.candidates.some(c=>c.status==='PASS'))||r[0];if(first)setRunId(first.id)})},[]);const selected=useMemo(()=>runs.find(r=>r.id===runId),[runs,runId]);const candidate=selected?.candidates[0];async function decide(){if(!selected||!candidate)return;setBusy(true);try{setReceipt(await api.createRelease({run_id:selected.id,candidate_model_id:candidate.model_id,workspace_id:workspace,environment:'pilot',requested_by:'portfolio-operator'}))}finally{setBusy(false)}}return <><Hero title="Rozhodnutí o nasazení" desc="Tady se z výsledku kontroly vytvoří finální, dohledatelné rozhodnutí pro konkrétní proces."/><div className="journey compactJourney"><div><span>1</span><b>Kontrola</b><small>změřili jsme důkazy</small></div><ArrowRight/><div><span>2</span><b>Rozhodnutí</b><small>aplikujeme pravidla</small></div><ArrowRight/><div><span>3</span><b>Záznam</b><small>uložíme proč a kdy</small></div></div>
<div className="split"><div className="panel pad"><h2>Vyberte výsledek</h2><label className="field"><span>Kontrola</span><select value={runId} onChange={e=>{setRunId(e.target.value);setReceipt(null)}}>{runs.map(r=><option key={r.id} value={r.id}>{useCaseLabel[r.use_case]||r.use_case} · {r.candidates[0]?.model_id}</option>)}</select></label><label className="field" style={{marginTop:10}}><span>Proces / workspace</span><select value={workspace} onChange={e=>setWorkspace(e.target.value)}>{workspaces.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label>{candidate&&<div style={{marginTop:12}}><SimpleStatus status={candidate.status}/></div>}<button className="btn primary bigCta" style={{marginTop:12,width:'100%'}} disabled={busy||!candidate} onClick={decide}>{busy?'Vyhodnocuji…':'Vytvořit rozhodnutí'}</button></div><div className="panel pad"><h2>Co toto rozhodnutí znamená?</h2><p className="plainText">Kontrola odpovídá na „jak si nová varianta vedla“. Rozhodnutí odpovídá na „máme ji pro tento proces pustit dál?“</p><div className="legend"><span className="status PASS">Lze nasadit</span><small>všechna pravidla splněna</small><span className="status REVIEW">Pozastavit</span><small>potřebuje člověka</small><span className="status BLOCK">Nenasazovat</span><small>kritický problém</small></div></div></div>
{receipt&&(()=>{const c=releaseCopy[receipt.decision];return <div className={'panel releaseResult '+c.tone}><div><div className="eye">FINÁLNÍ VERDIKT</div><h2>{c.title}</h2><p>{c.text}</p></div><div className="releaseNumbers"><span>Kvalita Δ <b>{receipt.quality_delta} pp</b></span><span>Cena Δ <b>{receipt.cost_delta_pct} %</b></span><span>Rychlost Δ <b>{receipt.p95_latency_delta_ms} ms</b></span></div><div className="muted">Záznam: {receipt.id}</div></div>})()}</>}

export function HowItWorks(){return <><Hero title="Jak to celé funguje" desc="Bez terminologie. Jeden problém, jeden proces a jedna otázka: je nová AI varianta opravdu lepší a dost bezpečná pro nasazení?"/><div className="howStack"><div className="panel pad howItem"><div className="stepBadge">1</div><div><h2>Máte současné řešení a chcete zkusit změnu</h2><p>Třeba jiný model pro čtení faktur. Nový model může být levnější nebo rychlejší, ale to samo o sobě nestačí.</p></div></div><div className="panel pad howItem"><div className="stepBadge">2</div><div><h2>Obě varianty dostanou stejné testovací případy</h2><p>Tak nevítězí marketing výrobce, ale měřitelný výsledek na konkrétním firemním procesu.</p></div></div><div className="panel pad howItem"><div className="stepBadge">3</div><div><h2>Změříme to, co je pro proces důležité</h2><p>Například správnost částky a účtu, halucinace, bezpečné použití nástrojů, cenu a rychlost.</p></div></div><div className="panel pad howItem"><div className="stepBadge">4</div><div><h2>Pravidla vytvoří jasný výsledek</h2><p><b>Prošlo</b>, <b>potřebuje kontrolu</b> nebo <b>nenasazovat</b>. Kritická chyba se neschová za hezký průměr.</p></div></div><div className="panel pad howItem"><div className="stepBadge">5</div><div><h2>Rozhodnutí se uloží jako důkaz</h2><p>Později lze dohledat, co bylo testováno, podle jakých pravidel a proč změna prošla nebo neprošla.</p></div></div></div><div className="simpleExample"><HelpCircle size={20}/><div><b>Příklad:</b> nový model zpracuje fakturu o 40 % levněji, ale občas změní číslo účtu. AI Evidence Gate ho zablokuje. Levnější chyba je pořád chyba.</div></div></>}
